# GENERATED BY VAPOUR
# DO NOT EDIT
#' Create a Vapour package
#' 
#' A light wrapper around [usethis::create_package()]
#' to create an R package and [scaffold()].
#' 
#' @param path Path where to create the package.
#' @param ... Passed to [usethis::create_package()].
#' 
#' @export
create = function(path,...) {
stopifnot((!missing(path)
))
if(dir.exists(path)
){
stop("directory already exists")

return(FALSE)
}
usethis::create_package(path, ...)

scaffold()


return(TRUE)
}
#' Scaffold a Vapour package
#' 
#' Setup a Vapour package, intended to be run
#' from the root of an R package.
#' 
#' @export
scaffold = function() {
dir.create("vp")
dir.create("inst")
usethis::use_build_ignore("vp")

}

